### ISSUE TITLE
callback functions

### ISSUE THREAD

**Issue by balint42** [turingou/sdk#2]
There should be clarification of how the callback functions given to the API methods work. In particular:

-The response argument in the callback does not fire `data`, `close` or `finish` events. Does this mean that the callback is only fired when `close` or `finish` have already fired? If so, is there a guarantee that the callback ever gets fired?

-The API methods return a response object. This response object _does_ fire a `data` event but does _not_ fire  `close` or `finish` - how comes?

It would be great to clarify these things - perhaps it is clear and I am just misunderstanding something?

**Comment by turingou** [comment]
The API methods return a normal `request` instance. SDK module does not wrap any kind of events. I think request's [documentation](https://github.com/request/request) may clarify these things.

Also, check more details about this in [libs/factory.js](https://github.com/turingou/sdk/blob/master/libs/factory.js)

**Comment by balint42** [comment]
Thanks for your reply. As for my second question: it is clear now, the returned object is a `request` instance and thus does not fire `close` or `finish`, but `response` events.
As for my first question: as far as I can tell after some reading the [request documentation](https://github.com/request/request) does not really clarify these things. One just has to trust that the callback is called somehow. :)
